/*1*/

SELECT count(DISTINCT NOMBRE_ESTACION) as cantidad_estaciones FROM barcelona_viajeros_por_franja_xlsx

/*2*/

SELECT NOMBRE_ESTACION FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION

/*3*/

SELECT NOMBRE_ESTACION, SUM(VIAJEROS_SUBIDOS), SUM(VIAJEROS_BAJADOS) FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION

/*4*/

SELECT NOMBRE_ESTACION, SUM(VIAJEROS_SUBIDOS), SUM(VIAJEROS_BAJADOS), VIAJEROS_SUBIDOS-VIAJEROS_BAJADOS AS DIFERENCIA FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION

/*5*/

SELECT TRAMO_HORARIO, NOMBRE_ESTACION,VIAJEROS_SUBIDOS FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
ORDER BY VIAJEROS_SUBIDOS DESC

/*6*/

SELECT NOMBRE_ESTACION, SUM(VIAJEROS_SUBIDOS)AS viajero_total FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION
ORDER BY viajero_total DESC
LIMIT 1

/*7*/

SELECT TRAMO_HORARIO, NOMBRE_ESTACION,VIAJEROS_BAJADOS FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
ORDER BY VIAJEROS_BAJADOS DESC

/*8*/

SELECT NOMBRE_ESTACION, SUM(VIAJEROS_BAJADOS)AS viajero_total FROM barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION
ORDER BY viajero_total DESC
LIMIT 1

/*9*/

SELECT TRAMO_HORARIO, NOMBRE_ESTACION, VIAJEROS_BAJADOS-VIAJEROS_SUBIDOS AS DIFERENCIA FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
ORDER BY DIFERENCIA DESC

/*10*/

SELECT NOMBRE_ESTACION, MAX(diferencia) AS maximo 
FROM (SELECT NOMBRE_ESTACION, (VIAJEROS_SUBIDOS-VIAJEROS_BAJADOS) as diferencia from barcelona_viajeros_por_franja_xlsx
GROUP BY NOMBRE_ESTACION)

/*11*/

SELECT NOMBRE_ESTACION, avg(VIAJEROS_SUBIDOS) AS promedio FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
 
/*12*/

SELECT NOMBRE_ESTACION, avg(VIAJEROS_SUBIDOS) AS promedio FROM barcelona_viajeros_por_franja_xlsx
GROUP BY TRAMO_HORARIO
HAVING VIAJEROS_SUBIDOS > promedio